Rules:
- '&31. Put your rules in a list here.'
- '&72. They can have colours!'
- '&33. Remember to follow YAML formatting rules. To use apostrophe, do this: it''s. Easy!'
- '&7Agree? Type &7/iagree'
Options:
  Move:
    Deny: false
    Message: false
  Talk:
    Deny: false
    Message: false
  BlockInteract:
    Deny: false
    Message: false
  EntityInteract:
    Deny: false
    Message: false
  BlockPlace:
    Deny: false
    Message: false
  BlockBreak:
    Deny: false
    Message: false
  InventoryClick:
    Deny: false
    Message: false
  ItemPickup:
    Deny: false
    Message: false
  ItemDrop:
    Deny: false
    Message: false
  ItemConsume:
    Deny: false
    Message: false
  ItemHeld:
    Deny: false
    Message: false
  ProjectileLaunch:
    Deny: false
    Message: false
  Attack:
    Deny: false
    Message: false
  Damage:
    Deny: false
    Message: false
  BucketEmpty:
    Deny: false
    Message: false
  BucketFill:
    Deny: false
    Message: false
  ToggleSneak:
    Deny: false
    Message: false
  ToggleSprint:
    Deny: false
    Message: false
  ExpChange:
    Deny: false
    Message: false
  PortalUsage:
    Deny: false
    Message: false
  RequireToReadRules: false
Messages:
  HasNotAgreed: '&aPlease read the &6/rules &aand agree with &6/iagree&6.'
  HasNotRead: '&cYou should read &7/rules &cfirst before agreeing to them.'
  JustAgreed: '&aThank you for agreeing with our rules, have fun!'
  HasAgreed: '&7You have already agreed to the rules.'
  DenyMessage: '&cYou can''t do this until you''ve agreed to the &7/rules.'
Tasks:
  SaveTask:
    Enabled: true
    Interval: 900
  MessageTask:
    Enabled: true
    Interval: 900